app/models.py
from flask_login import UserMixin
from . import db
from . import login_manager
from werkzeug.security import generate_password_hash, check_password_hash


class User(db.Model, UserMixin):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    email = db.Column(db.String(100), unique=True, nullable=False)
    password_hash = db.Column(db.String(30), nullable=False)
    products = db.relationship('Product', backref='seller', lazy='select', cascade='all, delete-orphan')

    def __repr__(self):
        return f"{self.username}"
    
    @property
    def password(self):
        raise AttributeError("password is not a readable attribute")
        
    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)
        
    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)
        

class Product(db.Model):
    __tablename__ = 'products'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    description = db.Column(db.Text, nullable=False)
    price = db.Column(db.Float, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)

    def __repr__(self):
        return f"{self.title}, {self.price}"
    
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, PasswordField, FloatField
from wtforms.validators import DataRequired, Email, Length

class AddUserForm(FlaskForm):
    username = StringField('Username:', validators=[DataRequired(), Length(min=4, max=20)])
    email = StringField('Email:', validators=[DataRequired(), Email(), Length(max=100)])
    password = PasswordField('Password:', validators=[DataRequired(), Length(min=8, max=30)])
    submit = SubmitField('Add User')

class AddProductForm(FlaskForm):
    title = StringField('Title:', validators=[DataRequired(), Length(max=100)])
    description = TextAreaField('Description:', validators=[DataRequired()])
    price = FloatField('Price:', validators=[DataRequired()])
    submit = SubmitField('Add Product')

class LoginForm(FlaskForm):
    email = StringField('Email:', validators=[DataRequired(), Email(), Length(max=100)])
    password = PasswordField('Password:', validators=[DataRequired(), Length(min=8, max=30)])
    submit = SubmitField('Login')

class DeleteUserForm(FlaskForm):
    email = StringField('Email:', validators=[DataRequired(), Email(), Length(max=100)])
    password = PasswordField('Password:', validators=[DataRequired(), Length(min=8, max=30)])
    submit = SubmitField("Delete User")

app/__init__.py
from flask import Flask
from config import config
from flask_sqlalchemy import SQLAlchemy

from flask_login import LoginManager

login_manager = LoginManager()
login_manager.login_view = "main.login"

db = SQLAlchemy()


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    with app.app_context():
        db.create_all()
    
    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint("main", __name__)

from . import views, errors

app/main/views.py
from flask import Flask, flash, render_template, request, redirect, url_for
from flask_login import login_required, current_user, login_user, logout_user

from ..models import User, Product
from . import main
from .. import db
from .forms import AddUserForm, AddProductForm, LoginForm, DeleteUserForm

@main.route("/")
def home():
    return render_template('home.html')

@main.route('/users')
def users():
    users = User.query.all()
    return render_template('users.html', users=users)

@main.route('/user/<int:user_id>')
def user_profile(user_id):
    user = User.query.get_or_404(user_id)
    return render_template('user_profile.html', user=user)

@main.route('/products')
def products():
    products = Product.query.all()
    return render_template('products.html', products=products)

@main.route('/product/<int:product_id>')
def product_detail(product_id):
    product = Product.query.get_or_404(product_id)
    return render_template('product_detail.html', product=product)

@main.route('/<int:user_id>/product/new', methods=['GET', 'POST'])
@login_required
def new_product(user_id):
    form = AddProductForm()
    if form.validate_on_submit():
        user = User.query.filter_by(id = user_id).first()
        product = Product(title=form.title.data, description=form.description.data, price=form.price.data)
        product.user_id = user.id
        db.session.add(product)
        db.session.commit()
        return redirect(url_for('main.product_detail', product_id = product.id))
    return render_template('new_product.html', form = form)

@main.route('/redirect_new_product')
def redirect_new_product():
    if current_user.is_authenticated:
        return redirect(url_for('main.new_product', user_id=current_user.id))
    else:
        flash('You must be logged in!', 'danger')
        return redirect(url_for('main.login'))
    
@main.route('/user/new', methods=['GET', 'POST'])
def new_user():
    form = AddUserForm()
    if form.validate_on_submit():
        search_email = User.query.filter_by(email=form.email.data).first()
        search_username = User.query.filter_by(username=form.username.data).first()
        if search_email is not None or search_username is not None:
            return render_template('new_user.html', form=form)
        user = User(username=form.username.data, email=form.email.data, password=form.password.data)
        db.session.add(user)
        db.session.commit()
        added = User.query.filter_by(email=form.email.data).first()
        login_user(added)
        flash('Account Created!', 'success')
        return redirect(url_for('main.user_profile', user_id=user.id))
    return render_template('new_user.html', form=form)

@main.route("/login", methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is not None and user.verify_password(form.password.data):
            login_user(user)
            flash('You have been logged in!', 'success')
            return redirect(url_for('main.user_profile', user_id=user.id))
        else:
            flash('Login unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)

@main.route("/logout")
@login_required
def logout():
    logout_user()
    flash('You have been logged out!', 'success')
    return redirect(url_for('main.users'))

@main.route("/delete_user/<int:user_id>", methods = ["GET", "POST"])
def delete_user(user_id):
    form = DeleteUserForm()
    if(form.validate_on_submit()):
        user = User.query.filter_by(id=user_id).first()
        if user is not None and user.verify_password(form.password.data):
            db.session.delete(user)
            db.session.commit()
            flash('Account Deleted!', 'success')
            return redirect(url_for('main.users'))
        flash('Wrong Email or Password!', 'danger')
        return redirect(url_for("main.delete_user", user_id = user_id))
    
    return render_template("delete_user.html", form = form, user_id=user_id)

@main.route("/delete_product/<int:product_id>", methods = ["GET", "POST"])
def delete_product(product_id):
    product = Product.query.filter_by(id=product_id).first()
    if product:
        db.session.delete(product)
        db.session.commit()
        flash('Product Deleted!', 'success')
        return redirect(url_for('main.products'))
    return redirect(url_for("main.product_detail", product_id = product_id))
    

app/templates/base.html
<!DOCTYPE html>
<html>
  {% block head %}
  <head>
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static',filename='css/base.css') }}"
    />
    <title>{% block title %}Marketplace{% endblock %}</title></head
  >{% endblock %}
  <body>
    <div class="nav-bar">
      <div class="nav-left">
        <a class="text-link" href=""><div class="nav-text">Marketplace</div></a>
        <div class="nav-btn"><a href="{{ url_for('main.home') }}">Home</a></div>
        <div class="nav-btn">
          <a href="{{ url_for('main.users') }}">Users</a>
        </div>
        <div class="nav-btn">
          <a href="{{ url_for('main.products') }}">Products</a>
        </div>
      </div>

      <div class="nav-right">
        <div class="nav-links">
          {% if current_user.is_authenticated %}
          <div class="nav-btn">
            <a
              href="{{ url_for('main.user_profile', user_id = current_user.id) }}"
              >Profile</a
            >
          </div>

          <div class="nav-btn">
            <a
              href="{{ url_for('main.redirect_new_product', user_id=current_user.id) }}"
              >Add product</a
            >
          </div>

          <div class="nav-btn">
            <a href="{{ url_for('main.logout') }}">Logout</a>
          </div>

          {% else %}
          <div class="nav-btn">
            <a
              href="{{ url_for('main.redirect_new_product', user_id=current_user.id) }}"
              >Add product</a
            >
          </div>
          <div class="nav-btn">
            <a href="{{ url_for('main.login') }}">Login</a>
          </div>
          <div class="nav-btn">
            <a href="{{ url_for('main.new_user') }}">Register</a>
          </div>
          {% endif %}
        </div>
      </div>
    </div>
    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %}
    <ul class="flash">
      {% for category, message in messages %}
      <li class="flash-item flash-{{ category }}">
        <span>{{ message }}</span>
        <button class="flash-dismiss" onclick="this.parentElement.remove()">
          &#x2715;
        </button>
      </li>
      {% endfor %}
    </ul>
    {% endif %} {% endwith %} {% block content %} {% endblock %}
  </body>
</html>

app/templates/delete_user.html
{% extends 'base.html' %} {% block title %}Delete Account{% endblock %} {% block
head %} {{ super() }}
<link
  rel="stylesheet"
  type="text/css"
  href="{{ url_for('static',filename='css/form.css') }}"
/>
{% endblock %} {% block content %}
<div class="container">
  <h1>Delete Account</h1>
  <form
    action="{{url_for('main.delete_user', user_id = user_id)}}"
    method="POST"
  >
    {{form.hidden_tag()}}
    <div class="form-input">{{ form.email.label }} {{ form.email }}</div>
    <div class="form-input">{{ form.password.label }} {{ form.password }}</div>
    <div class="delete-btn">{{ form.submit }}</div>
  </form>
</div>
{% endblock %}

app/templates/home.html
{% extends 'base.html' %} {% block title %}Home{% endblock %} {% block head %}
{{ super() }}
<link
  rel="stylesheet"
  type="text/css"
  href="{{ url_for('static',filename='css/home.css') }}"
/>
{% endblock %} {% block content %}
<div class="container">
  <h1>Welcome to Marketplace!</h1>
  <p>Create an account to sell and buy what you want.</p>
</div>
{% endblock %}

app/templates/login.html
{% extends 'base.html' %} {% block title %}Login{% endblock %} {% block head %}
{{ super() }}
<link
  rel="stylesheet"
  type="text/css"
  href="{{ url_for('static',filename='css/form.css') }}"
/>
{% endblock %}{% block content %}
<div class="container">
  <h1>Login</h1>
  <form action="{{url_for('main.login')}}" method="POST">
    {{ form.hidden_tag() }}
    <div class="form-input">{{ form.email.label }} {{ form.email }}</div>
    <div class="form-input">{{ form.password.label }} {{ form.password }}</div>
    <div class="submit-btn">{{ form.submit }}</div>
  </form>
</div>
{% endblock %}

app/templates/new_product.html
{% extends 'base.html' %}{% block title %}New Product{% endblock %}{% block head
%} {{ super() }}
<link
  rel="stylesheet"
  type="text/css"
  href="{{ url_for('static',filename='css/form.css') }}"
/>
{% endblock %} {% block content %}
<div class="container">
  <h1>New Product</h1>
  <form
    action="{{ url_for('main.new_product', user_id = current_user.id) }}"
    method="POST"
  >
    {{ form.hidden_tag() }}
    <div class="form-input">{{ form.title.label }} {{ form.title }}</div>
    <div class="form-text-area">
      {{ form.description.label }} {{ form.description }}
    </div>
    <div class="form-input">{{ form.price.label }} {{ form.price }}</div>
    <div class="submit-btn">{{ form.submit }}</div>
  </form>
</div>
{% endblock %}

app/templates/new_user.html
{% extends 'base.html' %} {% block title %}New Account{% endblock %}{% block
head %} {{ super() }}
<link
  rel="stylesheet"
  type="text/css"
  href="{{ url_for('static',filename='css/form.css') }}"
/>
{% endblock %} {% block content %}
<div class="container">
  <h1>Register</h1>
  <form action="{{url_for('main.new_user')}}" method="POST">
    {{ form.hidden_tag() }}
    <div class="form-input">{{ form.username.label }} {{ form.username }}</div>
    <div class="form-input">{{ form.email.label }} {{ form.email }}</div>
    <div class="form-input">{{ form.password.label }} {{ form.password }}</div>
    <div class="submit-btn">{{ form.submit }}</div>
  </form>
</div>
{% endblock %}

app/templates/product_detail.html
{% extends 'base.html' %} {% block title %}Product Detail{% endblock %} {% block
head %} {{ super() }}
<link
  rel="stylesheet"
  type="text/css"
  href="{{ url_for('static',filename='css/product_detail.css') }}"
/>
{% endblock %} {% block content %}
<div class="container">
  <div class="product-name">Product Name: {{ product.title }}</div>
  <div class="product-des">Description: {{ product.description }}</div>
  <div class="product-des">Price: {{ product.price }}</div>
  <div class="product-des">Seller: {{ product.seller }}</div>
  {% if current_user.id == product.user_id %}
  <div class="delete-btn">
    <a href="{{ url_for('main.delete_product', product_id = product.id)}}"
      >Delete Product</a
    >
  </div>
  {% endif %}
</div>
{% endblock %}

app/templates/products.html
{% extends 'base.html' %} {% block title %}All Products{% endblock %}{% block
head %} {{ super() }}
<link
  rel="stylesheet"
  type="text/css"
  href="{{ url_for('static',filename='css/products.css') }}"
/>
{% endblock %} {% block content %}
<h1>All Products</h1>
<div class="container">
  {% for product in products %}
  <div class="product-holder">
    <a
      class="center"
      href="{{ url_for('main.product_detail', product_id=product.id) }}"
      >{{ product.title }}</a
    >
    <div class="product-des"><b>Description:</b> {{ product.description }}</div>
    <div class="product-des"><b>Price:</b> {{ product.price }}</div>
    <div class="product-des"><b>Seller:</b> {{ product.seller }}</div>
  </div>
  {% endfor %}
</div>
{% endblock %}

app/templates/user_profile.html
{% extends 'base.html' %} {% block title %}{{ user.username }}{% endblock %} {%
block head %} {{ super() }}
<link
  rel="stylesheet"
  type="text/css"
  href="{{ url_for('static',filename='css/user_profile.css') }}"
/>
{% endblock %}{% block content %}
<div class="container">
  <div class="username">Username: {{ user.username }}</div>
  {% if current_user.email == user.email%}
  <div>
    <a href="{{ url_for('main.delete_user', user_id = user.id)}}"
      >Delete Account</a
    >
  </div>
  {% endif %}
  <div class="email">Email: {{ user.email }}</div>
  <div class="my-products">My Products:</div>
  <div class="products">
    {% for product in user.products %}
    <div class="product-holder">
      <a
        class="center"
        href="{{ url_for('main.product_detail', product_id=product.id) }}"
        >{{ product.title }}</a
      >
      <div class="product-des">
        <b>Description:</b> {{ product.description }}
      </div>
      <div class="product-des"><b>Price:</b> {{ product.price }}</div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

app/templates/users.html
{% extends 'base.html' %} {% block title %}All Users{% endblock %}{% block head
%} {{ super() }}
<link
  rel="stylesheet"
  type="text/css"
  href="{{ url_for('static',filename='css/users.css') }}"
/>
{% endblock %} {% block content %}
<h1>All Users</h1>
<div class="container">
  {% for user in users %}
  <a
    class="name-holder"
    href="{{ url_for('main.user_profile', user_id=user.id) }}"
    ><div class="center">{{ user.username }}</div>
  </a>
  {% endfor %}
</div>
{% endblock %}